# Generated by Django 5.1.7 on 2025-03-28 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='hr_app.employee')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
    ]
