# Generated by Django 5.1.7 on 2025-03-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0002_timelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelog',
            options={'ordering': ['-check_in'], 'verbose_name': 'დროის აღრიცხვა', 'verbose_name_plural': 'დროის აღრიცხვები'},
        ),
    ]
