# Generated by Django 5.1.7 on 2025-03-28 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_alter_timelog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-check_in'], 'verbose_name': 'დროის ჩანაწერი', 'verbose_name_plural': 'დროის ჩანაწერები'},
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='areas_for_improvement',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='performance_rating',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='hours_worked',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='overtime',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='communication_rating',
            field=models.IntegerField(choices=[(1, 'არადამაკმაყოფილებელი'), (2, 'საჭიროებს გაუმჯობესებას'), (3, 'დამაკმაყოფილებელი'), (4, 'კარგი'), (5, 'შესანიშნავი')], default=3),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='initiative_rating',
            field=models.IntegerField(choices=[(1, 'არადამაკმაყოფილებელი'), (2, 'საჭიროებს გაუმჯობესებას'), (3, 'დამაკმაყოფილებელი'), (4, 'კარგი'), (5, 'შესანიშნავი')], default=3),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='productivity_rating',
            field=models.IntegerField(choices=[(1, 'არადამაკმაყოფილებელი'), (2, 'საჭიროებს გაუმჯობესებას'), (3, 'დამაკმაყოფილებელი'), (4, 'კარგი'), (5, 'შესანიშნავი')], default=3),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='quality_rating',
            field=models.IntegerField(choices=[(1, 'არადამაკმაყოფილებელი'), (2, 'საჭიროებს გაუმჯობესებას'), (3, 'დამაკმაყოფილებელი'), (4, 'კარგი'), (5, 'შესანიშნავი')], default=3),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_period_end',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='review_period_start',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='teamwork_rating',
            field=models.IntegerField(choices=[(1, 'არადამაკმაყოფილებელი'), (2, 'საჭიროებს გაუმჯობესებას'), (3, 'დამაკმაყოფილებელი'), (4, 'კარგი'), (5, 'შესანიშნავი')], default=3),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='check_in',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='შემოსვლის დრო'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='გასვლის დრო'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP მისამართი'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, verbose_name='აღწერა'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='დასახელება'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_app.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('vacation', 'შვებულება'), ('sick', 'ავადმყოფობა'), ('other', 'სხვა')], max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='review_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='hr_app.employee'),
        ),
        migrations.CreateModel(
            name='PerformanceGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'მიმდინარე'), ('completed', 'დასრულებული'), ('cancelled', 'გაუქმებული')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_goals', to='hr_app.employee')),
            ],
        ),
    ]
