# Generated by Django 5.1.7 on 2025-03-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0005_remove_employee_address_remove_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'მამრობითი'), ('female', 'მდედრობითი'), ('other', 'სხვა')], max_length=10, null=True, verbose_name='სქესი'),
        ),
    ]
