# Generated by Django 5.1.7 on 2025-03-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0006_alter_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
